### ISSUE TITLE
(mobile-login component) ошибка изменения размеров input полей

### ISSUE THREAD

**Issue by Thwacka** [Thwacka/uniAPI#33]
Как вариант это вернутся к старым добрым медиазапросам. Но эти медиазапросы адрисовать только инпут полям и кнопке. Расположение wrapper и form-content не трогать.

**Comment by KostaSamsonow** [comment]
медиа запросы не помогли, так что пришлось отказаться от параметра height

**Comment by Thwacka** [comment]
Ну за то теперь выглядит не плохо. Так держать)
